In [2]:
import numpy as np

print("⭐ NumPy Array Operations Project ⭐\n")

arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("\n2D Array:\n", arr2)

print("\n👉 Sum of 1D array:", np.sum(arr1))
print("👉 Maximum value:", np.max(arr1))
print("👉 Minimum value:", np.min(arr1))
print("👉 Multiply each element by 2:", arr1 * 2)

print("\n👉 Shape of 2D array:", arr2.shape)
print("👉 Sum of all elements:", np.sum(arr2))
print("👉 Row-wise sum:", np.sum(arr2, axis=1))
print("👉 Column-wise sum:", np.sum(arr2, axis=0))

print("\n👉 First two rows:\n", arr2[:2])
print("👉 First column:\n", arr2[:, 0])
print("👉 Middle element:", arr2[1, 1])

reshaped = arr1.reshape(5, 1)
print("\n👉 Reshaped 1D array to 2D (5x1):\n", reshaped)


⭐ NumPy Array Operations Project ⭐

1D Array: [10 20 30 40 50]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

👉 Sum of 1D array: 150
👉 Maximum value: 50
👉 Minimum value: 10
👉 Multiply each element by 2: [ 20  40  60  80 100]

👉 Shape of 2D array: (3, 3)
👉 Sum of all elements: 45
👉 Row-wise sum: [ 6 15 24]
👉 Column-wise sum: [12 15 18]

👉 First two rows:
 [[1 2 3]
 [4 5 6]]
👉 First column:
 [1 4 7]
👉 Middle element: 5

👉 Reshaped 1D array to 2D (5x1):
 [[10]
 [20]
 [30]
 [40]
 [50]]
