In [1]:
import pandas as pd
df = pd.read_csv("students.csv")
df

Name  Math  Science  English
0   Riya    88       92       85
1  Kiran    75       80       78
2  Arjun    90       85       88
3  Rohit    70       65       72
4  Meera    95       98       94

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("students.csv")
print("Student Data:")
print(df)

math_mean = np.mean(df["Math"])
science_mean = np.mean(df["Science"])
english_mean = np.mean(df["English"])

print("\nSubject Averages:")
print("Math Mean:", math_mean)
print("Science Mean:", science_mean)
print("English Mean:", english_mean)

marks_array = np.array(df.iloc[:3, 1:])
reshaped = marks_array.reshape(3, 3)

print("\nReshaped Marks Array (3 students x 3 subjects):")
print(reshaped)

average_series = pd.Series({
    "Math": math_mean,
    "Science": science_mean,
    "English": english_mean
})

print("\nAverage Marks Series:")
print(average_series)

df["Total"] = df["Math"] + df["Science"] + df["English"]
print("\nDataFrame with Total Marks:")
print(df)

Student Data:
    Name  Math  Science  English
0   Riya    88       92       85
1  Kiran    75       80       78
2  Arjun    90       85       88
3  Rohit    70       65       72
4  Meera    95       98       94

Subject Averages:
Math Mean: 83.6
Science Mean: 84.0
English Mean: 83.4

Reshaped Marks Array (3 students x 3 subjects):
[[88 92 85]
 [75 80 78]
 [90 85 88]]

Average Marks Series:
Math       83.6
Science    84.0
English    83.4
dtype: float64

DataFrame with Total Marks:
    Name  Math  Science  English  Total
0   Riya    88       92       85    265
1  Kiran    75       80       78    233
2  Arjun    90       85       88    263
3  Rohit    70       65       72    207
4  Meera    95       98       94    287
